# Generated by Django 6.0.3 on 2026-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
