# Generated by Django 6.0.3 on 2026-03-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_produto_estoque_atual_produto_estoque_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
